export const GenerosEnum = {
    // Gêneros Literários
    ACAO: "ação",
    AVENTURA: "aventura",
    DRAMA: "drama",
    FANTASIA: "fantasia",
    ROMANCE: "romance",
    SUSPENSE: "suspense",
    FICCAO_CIENTIFICA: "ficção científica",
    TERROR: "terror",
    MISTERIO: "mistério",
    POLICIAL: "policial",
    THRILLER: "thriller",
    DISTOPIA: "distopia",
    COMEDIA: "comédia",
    CHICK_LIT: "chick-lit",
    YOUNG_ADULT: "young adult",
    INFANTIL: "infantil",
    MITOLOGIA: "mitologia",
    FANFIC: "fanfic",
    POESIA: "poesia",
    CONTO: "conto",
    CRONICA: "crônica",
    ENSAIO: "ensaio",
    EPOPEIA: "epopeia",
    SATIRA: "sátira",
    NOVELA: "novela",

    // Gêneros Não Literários
    BIOGRAFIA: "biografia",
    AUTOBIOGRAFIA: "autobiografia",
    MEMORIAS: "memórias",
    REPORTAGEM: "reportagem",
    JORNALISTICO: "jornalístico",
    HISTORICO: "histórico",
    FILOSOFICO: "filosófico",
    RELIGIOSO: "religioso",
    DIDATICO: "didático",
    CIENTIFICO: "científico",
    MANUAL_TECNICO: "manual técnico",
    AUTOAJUDA: "autoajuda",
    DISCURSO: "discurso",
    ENTREVISTA: "entrevista",
    ORATORIA: "oratória",
    DOCUMENTARIO: "documentário",
};